/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "control.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ControlCommand, ControlCommand, AUTO)


PB_BIND(ControlData, ControlData, 2)



