/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CONTROL_PB_H_INCLUDED
#define PB_CONTROL_PB_H_INCLUDED
#include "utils/pb.h"
#include "drive.pb.h"
#include "relays.pb.h"
#include "version.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ControlCommand {
    bool has_version;
    Version version;
    bool has_drive;
    DriveCommand drive;
    bool has_relays;
    RelaysCommand relays;
} ControlCommand;

typedef struct _ControlData {
    bool has_version;
    Version version;
    bool has_drive;
    DriveData drive;
    bool has_relays;
    RelaysData relays;
} ControlData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ControlCommand_init_default              {false, Version_init_default, false, DriveCommand_init_default, false, RelaysCommand_init_default}
#define ControlData_init_default                 {false, Version_init_default, false, DriveData_init_default, false, RelaysData_init_default}
#define ControlCommand_init_zero                 {false, Version_init_zero, false, DriveCommand_init_zero, false, RelaysCommand_init_zero}
#define ControlData_init_zero                    {false, Version_init_zero, false, DriveData_init_zero, false, RelaysData_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ControlCommand_version_tag               1
#define ControlCommand_drive_tag                 2
#define ControlCommand_relays_tag                3
#define ControlData_version_tag                  1
#define ControlData_drive_tag                    2
#define ControlData_relays_tag                   3

/* Struct field encoding specification for nanopb */
#define ControlCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  drive,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  relays,            3)
#define ControlCommand_CALLBACK NULL
#define ControlCommand_DEFAULT NULL
#define ControlCommand_version_MSGTYPE Version
#define ControlCommand_drive_MSGTYPE DriveCommand
#define ControlCommand_relays_MSGTYPE RelaysCommand

#define ControlData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  drive,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  relays,            3)
#define ControlData_CALLBACK NULL
#define ControlData_DEFAULT NULL
#define ControlData_version_MSGTYPE Version
#define ControlData_drive_MSGTYPE DriveData
#define ControlData_relays_MSGTYPE RelaysData

extern const pb_msgdesc_t ControlCommand_msg;
extern const pb_msgdesc_t ControlData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ControlCommand_fields &ControlCommand_msg
#define ControlData_fields &ControlData_msg

/* Maximum encoded size of messages (where known) */
#define CONTROL_PB_H_MAX_SIZE                    ControlData_size
#define ControlCommand_size                      141
#define ControlData_size                         320

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
