/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "lidar.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LidarCartesianPoint, LidarCartesianPoint, AUTO)


PB_BIND(LidarPolarPoint, LidarPolarPoint, AUTO)


PB_BIND(LidarPointCloud, LidarPointCloud, AUTO)



