/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_LIDAR_PB_H_INCLUDED
#define PB_LIDAR_PB_H_INCLUDED
#include "utils/pb.h"
#include "version.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _LidarCartesianPoint {
    float x;
    float y;
} LidarCartesianPoint;

typedef struct _LidarPolarPoint {
    float angle;
    float distance;
} LidarPolarPoint;

typedef struct _LidarPointCloud {
    pb_callback_t cartesian;
    pb_callback_t polar;
    bool has_version;
    Version version;
} LidarPointCloud;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LidarCartesianPoint_init_default         {0, 0}
#define LidarPolarPoint_init_default             {0, 0}
#define LidarPointCloud_init_default             {{{NULL}, NULL}, {{NULL}, NULL}, false, Version_init_default}
#define LidarCartesianPoint_init_zero            {0, 0}
#define LidarPolarPoint_init_zero                {0, 0}
#define LidarPointCloud_init_zero                {{{NULL}, NULL}, {{NULL}, NULL}, false, Version_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define LidarCartesianPoint_x_tag                1
#define LidarCartesianPoint_y_tag                2
#define LidarPolarPoint_angle_tag                1
#define LidarPolarPoint_distance_tag             2
#define LidarPointCloud_cartesian_tag            1
#define LidarPointCloud_polar_tag                2
#define LidarPointCloud_version_tag              3

/* Struct field encoding specification for nanopb */
#define LidarCartesianPoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2)
#define LidarCartesianPoint_CALLBACK NULL
#define LidarCartesianPoint_DEFAULT NULL

#define LidarPolarPoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    angle,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    distance,          2)
#define LidarPolarPoint_CALLBACK NULL
#define LidarPolarPoint_DEFAULT NULL

#define LidarPointCloud_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  cartesian,         1) \
X(a, CALLBACK, REPEATED, MESSAGE,  polar,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           3)
#define LidarPointCloud_CALLBACK pb_default_field_callback
#define LidarPointCloud_DEFAULT NULL
#define LidarPointCloud_cartesian_MSGTYPE LidarCartesianPoint
#define LidarPointCloud_polar_MSGTYPE LidarPolarPoint
#define LidarPointCloud_version_MSGTYPE Version

extern const pb_msgdesc_t LidarCartesianPoint_msg;
extern const pb_msgdesc_t LidarPolarPoint_msg;
extern const pb_msgdesc_t LidarPointCloud_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LidarCartesianPoint_fields &LidarCartesianPoint_msg
#define LidarPolarPoint_fields &LidarPolarPoint_msg
#define LidarPointCloud_fields &LidarPointCloud_msg

/* Maximum encoded size of messages (where known) */
/* LidarPointCloud_size depends on runtime parameters */
#define LIDAR_PB_H_MAX_SIZE                      LidarCartesianPoint_size
#define LidarCartesianPoint_size                 10
#define LidarPolarPoint_size                     10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
