/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_RELAYS_PB_H_INCLUDED
#define PB_RELAYS_PB_H_INCLUDED
#include "utils/pb.h"
#include "utils.pb.h"
#include "version.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RelaysCommand {
    bool has_version;
    Version version;
    /* Turn the following devices on or off */
    BoolState back_left_motor;
    BoolState back_right_motor;
    BoolState front_left_motor;
    BoolState front_right_motor;
    BoolState middle_left_motor;
    BoolState middle_right_motor;
    BoolState arm;
    BoolState science;
    /* Special commands */
    BoolState bypass;
} RelaysCommand;

typedef struct _RelaysData {
    bool has_version;
    Version version;
    /* Whether the following devices are on or off */
    BoolState back_left_motor;
    BoolState back_right_motor;
    BoolState front_left_motor;
    BoolState front_right_motor;
    BoolState middle_left_motor;
    BoolState middle_right_motor;
    BoolState arm;
    BoolState science;
    BoolState bypass;
    BoolState mechanical_override;
    /* Special data */
    float battery_voltage;
} RelaysData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RelaysCommand_init_default               {false, Version_init_default, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN}
#define RelaysData_init_default                  {false, Version_init_default, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, 0}
#define RelaysCommand_init_zero                  {false, Version_init_zero, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN}
#define RelaysData_init_zero                     {false, Version_init_zero, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, _BoolState_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define RelaysCommand_version_tag                1
#define RelaysCommand_back_left_motor_tag        2
#define RelaysCommand_back_right_motor_tag       3
#define RelaysCommand_front_left_motor_tag       4
#define RelaysCommand_front_right_motor_tag      5
#define RelaysCommand_middle_left_motor_tag      6
#define RelaysCommand_middle_right_motor_tag     7
#define RelaysCommand_arm_tag                    8
#define RelaysCommand_science_tag                9
#define RelaysCommand_bypass_tag                 11
#define RelaysData_version_tag                   1
#define RelaysData_back_left_motor_tag           2
#define RelaysData_back_right_motor_tag          3
#define RelaysData_front_left_motor_tag          4
#define RelaysData_front_right_motor_tag         5
#define RelaysData_middle_left_motor_tag         6
#define RelaysData_middle_right_motor_tag        7
#define RelaysData_arm_tag                       8
#define RelaysData_science_tag                   9
#define RelaysData_bypass_tag                    11
#define RelaysData_mechanical_override_tag       12
#define RelaysData_battery_voltage_tag           13

/* Struct field encoding specification for nanopb */
#define RelaysCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           1) \
X(a, STATIC,   SINGULAR, UENUM,    back_left_motor,   2) \
X(a, STATIC,   SINGULAR, UENUM,    back_right_motor,   3) \
X(a, STATIC,   SINGULAR, UENUM,    front_left_motor,   4) \
X(a, STATIC,   SINGULAR, UENUM,    front_right_motor,   5) \
X(a, STATIC,   SINGULAR, UENUM,    middle_left_motor,   6) \
X(a, STATIC,   SINGULAR, UENUM,    middle_right_motor,   7) \
X(a, STATIC,   SINGULAR, UENUM,    arm,               8) \
X(a, STATIC,   SINGULAR, UENUM,    science,           9) \
X(a, STATIC,   SINGULAR, UENUM,    bypass,           11)
#define RelaysCommand_CALLBACK NULL
#define RelaysCommand_DEFAULT NULL
#define RelaysCommand_version_MSGTYPE Version

#define RelaysData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           1) \
X(a, STATIC,   SINGULAR, UENUM,    back_left_motor,   2) \
X(a, STATIC,   SINGULAR, UENUM,    back_right_motor,   3) \
X(a, STATIC,   SINGULAR, UENUM,    front_left_motor,   4) \
X(a, STATIC,   SINGULAR, UENUM,    front_right_motor,   5) \
X(a, STATIC,   SINGULAR, UENUM,    middle_left_motor,   6) \
X(a, STATIC,   SINGULAR, UENUM,    middle_right_motor,   7) \
X(a, STATIC,   SINGULAR, UENUM,    arm,               8) \
X(a, STATIC,   SINGULAR, UENUM,    science,           9) \
X(a, STATIC,   SINGULAR, UENUM,    bypass,           11) \
X(a, STATIC,   SINGULAR, UENUM,    mechanical_override,  12) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_voltage,  13)
#define RelaysData_CALLBACK NULL
#define RelaysData_DEFAULT NULL
#define RelaysData_version_MSGTYPE Version

extern const pb_msgdesc_t RelaysCommand_msg;
extern const pb_msgdesc_t RelaysData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RelaysCommand_fields &RelaysCommand_msg
#define RelaysData_fields &RelaysData_msg

/* Maximum encoded size of messages (where known) */
#define RELAYS_PB_H_MAX_SIZE                     RelaysData_size
#define RelaysCommand_size                       42
#define RelaysData_size                          49

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
