/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "relays.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RelaysCommand, RelaysCommand, AUTO)


PB_BIND(RelaysData, RelaysData, AUTO)



