/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_SCIENCE_PB_H_INCLUDED
#define PB_SCIENCE_PB_H_INCLUDED
#include "utils/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ScienceCommand {
    bool dig;
    bool spin_carousel_tube;
    bool spin_carousel_section;
    float vacuum_suck;
    int32_t carousel_angle;
    int32_t carousel_linear_position;
    int32_t test_linear_position;
    int32_t vacuum_linear_position;
    bool pump1;
    bool pump2;
    bool pump3;
    bool pump4;
    int32_t dirtRelease;
} ScienceCommand;

typedef struct _ScienceData {
    float co2;
    float humidity;
    float methane;
    float pH;
    float temperature;
} ScienceData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ScienceCommand_init_default              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ScienceData_init_default                 {0, 0, 0, 0, 0}
#define ScienceCommand_init_zero                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ScienceData_init_zero                    {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ScienceCommand_dig_tag                   1
#define ScienceCommand_spin_carousel_tube_tag    2
#define ScienceCommand_spin_carousel_section_tag 3
#define ScienceCommand_vacuum_suck_tag           4
#define ScienceCommand_carousel_angle_tag        5
#define ScienceCommand_carousel_linear_position_tag 6
#define ScienceCommand_test_linear_position_tag  7
#define ScienceCommand_vacuum_linear_position_tag 8
#define ScienceCommand_pump1_tag                 9
#define ScienceCommand_pump2_tag                 10
#define ScienceCommand_pump3_tag                 11
#define ScienceCommand_pump4_tag                 12
#define ScienceCommand_dirtRelease_tag           13
#define ScienceData_co2_tag                      1
#define ScienceData_humidity_tag                 2
#define ScienceData_methane_tag                  3
#define ScienceData_pH_tag                       4
#define ScienceData_temperature_tag              5

/* Struct field encoding specification for nanopb */
#define ScienceCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     dig,               1) \
X(a, STATIC,   SINGULAR, BOOL,     spin_carousel_tube,   2) \
X(a, STATIC,   SINGULAR, BOOL,     spin_carousel_section,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    vacuum_suck,       4) \
X(a, STATIC,   SINGULAR, INT32,    carousel_angle,    5) \
X(a, STATIC,   SINGULAR, INT32,    carousel_linear_position,   6) \
X(a, STATIC,   SINGULAR, INT32,    test_linear_position,   7) \
X(a, STATIC,   SINGULAR, INT32,    vacuum_linear_position,   8) \
X(a, STATIC,   SINGULAR, BOOL,     pump1,             9) \
X(a, STATIC,   SINGULAR, BOOL,     pump2,            10) \
X(a, STATIC,   SINGULAR, BOOL,     pump3,            11) \
X(a, STATIC,   SINGULAR, BOOL,     pump4,            12) \
X(a, STATIC,   SINGULAR, INT32,    dirtRelease,      13)
#define ScienceCommand_CALLBACK NULL
#define ScienceCommand_DEFAULT NULL

#define ScienceData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    co2,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    methane,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    pH,                4) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       5)
#define ScienceData_CALLBACK NULL
#define ScienceData_DEFAULT NULL

extern const pb_msgdesc_t ScienceCommand_msg;
extern const pb_msgdesc_t ScienceData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ScienceCommand_fields &ScienceCommand_msg
#define ScienceData_fields &ScienceData_msg

/* Maximum encoded size of messages (where known) */
#define ScienceCommand_size                      74
#define ScienceData_size                         25

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
