/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SUBSYSTEMS_PB_H_INCLUDED
#define PB_SUBSYSTEMS_PB_H_INCLUDED
#include "utils/pb.h"
#include "core.pb.h"
#include "version.pb.h"
#include "utils.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SubsystemsCommand {
    bool zero_imu;
    bool has_version;
    Version version;
} SubsystemsCommand;

typedef struct _SubsystemsData {
    bool has_version;
    Version version;
    pb_callback_t connected_devices;
    BoolState gps_connected;
    BoolState imu_connected;
} SubsystemsData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SubsystemsCommand_init_default           {0, false, Version_init_default}
#define SubsystemsData_init_default              {false, Version_init_default, {{NULL}, NULL}, _BoolState_MIN, _BoolState_MIN}
#define SubsystemsCommand_init_zero              {0, false, Version_init_zero}
#define SubsystemsData_init_zero                 {false, Version_init_zero, {{NULL}, NULL}, _BoolState_MIN, _BoolState_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define SubsystemsCommand_zero_imu_tag           1
#define SubsystemsCommand_version_tag            2
#define SubsystemsData_version_tag               1
#define SubsystemsData_connected_devices_tag     2
#define SubsystemsData_gps_connected_tag         3
#define SubsystemsData_imu_connected_tag         4

/* Struct field encoding specification for nanopb */
#define SubsystemsCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     zero_imu,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           2)
#define SubsystemsCommand_CALLBACK NULL
#define SubsystemsCommand_DEFAULT NULL
#define SubsystemsCommand_version_MSGTYPE Version

#define SubsystemsData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           1) \
X(a, CALLBACK, REPEATED, UENUM,    connected_devices,   2) \
X(a, STATIC,   SINGULAR, UENUM,    gps_connected,     3) \
X(a, STATIC,   SINGULAR, UENUM,    imu_connected,     4)
#define SubsystemsData_CALLBACK pb_default_field_callback
#define SubsystemsData_DEFAULT NULL
#define SubsystemsData_version_MSGTYPE Version

extern const pb_msgdesc_t SubsystemsCommand_msg;
extern const pb_msgdesc_t SubsystemsData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SubsystemsCommand_fields &SubsystemsCommand_msg
#define SubsystemsData_fields &SubsystemsData_msg

/* Maximum encoded size of messages (where known) */
/* SubsystemsData_size depends on runtime parameters */
#define SUBSYSTEMS_PB_H_MAX_SIZE                 SubsystemsCommand_size
#define SubsystemsCommand_size                   26

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
