/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SCIENCE_PB_H_INCLUDED
#define PB_SCIENCE_PB_H_INCLUDED
#include "utils/pb.h"
#include "version.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* / The state of a servo. If undefined, don't open or close. */
typedef enum _ServoState {
    ServoState_SERVO_STATE_UNDEFINED = 0,
    ServoState_SERVO_OPEN = 1,
    ServoState_SERVO_CLOSE = 2
} ServoState;

/* / The state of a pump. If undefined: don't do anything. If fill: turn on, wait, then turn off. */
typedef enum _PumpState {
    PumpState_PUMP_STATE_UNDEFINED = 0,
    PumpState_PUMP_ON = 1,
    PumpState_PUMP_OFF = 2,
    PumpState_FILL = 3
} PumpState;

/* / The state of the science subsystem. If not COLLECT_DATA, don't stream data at all. */
typedef enum _ScienceState {
    ScienceState_SCIENCE_STATE_UNDEFINED = 0,
    ScienceState_COLLECT_DATA = 1,
    ScienceState_STOP_COLLECTING = 2
} ScienceState;

/* / A command for the carousel and funnel to follow. */
typedef enum _CarouselCommand {
    CarouselCommand_CAROUSEL_COMMAND_UNDEFINED = 0,
    CarouselCommand_NEXT_TUBE = 1,
    CarouselCommand_PREV_TUBE = 2,
    CarouselCommand_NEXT_SECTION = 3,
    CarouselCommand_PREV_SECTION = 4,
    CarouselCommand_FILL_TUBE = 5,
    CarouselCommand_FILL_SECTION = 6
} CarouselCommand;

/* Struct definitions */
/* / Command to control the auger */
typedef struct _AugerCommand {
    /* Speed of the auger in RPM, between 0.0 - 0.4 */
    bool has_speed_rpm;
    float speed_rpm;
    ServoState upper_servo;
    ServoState lower_servo;
} AugerCommand;

/* / Data from the auger */
typedef struct _AugerData {
    ServoState lower_servo;
    ServoState upper_servo;
    /* Distance to ground, in centimeters */
    float distance_to_ground_cm;
    float current;
} AugerData;

/* / Command for linear slider */
typedef struct _LinearSliderCommand {
    bool clear_stallstop;
} LinearSliderCommand;

/* / Data from linear slider */
typedef struct _LinearSliderData {
    bool is_stalled;
} LinearSliderData;

/* / A command to the science subsystem. */
typedef struct _ScienceCommand {
    /* Individual control over each motor. Indicates steps to move */
    float carousel_motor;
    /* Control over other hardware */
    PumpState pumps;
    CarouselCommand carousel;
    /* High level commands */
    bool calibrate;
    bool stop;
    int32_t sample;
    ScienceState state;
    bool has_version;
    Version version;
    bool has_auger;
    AugerCommand auger;
    bool has_linear_slider;
    LinearSliderCommand linear_slider;
} ScienceCommand;

/* / Data coming from the science subsystem. */
typedef struct _ScienceData {
    /* High-level data */
    int32_t sample;
    ScienceState state;
    /* Sensor data */
    float co2;
    float humidity;
    float temperature;
    bool has_version;
    Version version;
    bool has_auger;
    AugerData auger;
    bool has_linear_slider;
    LinearSliderData linear_slider;
} ScienceData;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ServoState_MIN ServoState_SERVO_STATE_UNDEFINED
#define _ServoState_MAX ServoState_SERVO_CLOSE
#define _ServoState_ARRAYSIZE ((ServoState)(ServoState_SERVO_CLOSE+1))

#define _PumpState_MIN PumpState_PUMP_STATE_UNDEFINED
#define _PumpState_MAX PumpState_FILL
#define _PumpState_ARRAYSIZE ((PumpState)(PumpState_FILL+1))

#define _ScienceState_MIN ScienceState_SCIENCE_STATE_UNDEFINED
#define _ScienceState_MAX ScienceState_STOP_COLLECTING
#define _ScienceState_ARRAYSIZE ((ScienceState)(ScienceState_STOP_COLLECTING+1))

#define _CarouselCommand_MIN CarouselCommand_CAROUSEL_COMMAND_UNDEFINED
#define _CarouselCommand_MAX CarouselCommand_FILL_SECTION
#define _CarouselCommand_ARRAYSIZE ((CarouselCommand)(CarouselCommand_FILL_SECTION+1))

#define AugerCommand_upper_servo_ENUMTYPE ServoState
#define AugerCommand_lower_servo_ENUMTYPE ServoState

#define AugerData_lower_servo_ENUMTYPE ServoState
#define AugerData_upper_servo_ENUMTYPE ServoState



#define ScienceCommand_pumps_ENUMTYPE PumpState
#define ScienceCommand_carousel_ENUMTYPE CarouselCommand
#define ScienceCommand_state_ENUMTYPE ScienceState

#define ScienceData_state_ENUMTYPE ScienceState


/* Initializer values for message structs */
#define AugerCommand_init_default                {false, 0, _ServoState_MIN, _ServoState_MIN}
#define AugerData_init_default                   {_ServoState_MIN, _ServoState_MIN, 0, 0}
#define LinearSliderCommand_init_default         {0}
#define LinearSliderData_init_default            {0}
#define ScienceCommand_init_default              {0, _PumpState_MIN, _CarouselCommand_MIN, 0, 0, 0, _ScienceState_MIN, false, Version_init_default, false, AugerCommand_init_default, false, LinearSliderCommand_init_default}
#define ScienceData_init_default                 {0, _ScienceState_MIN, 0, 0, 0, false, Version_init_default, false, AugerData_init_default, false, LinearSliderData_init_default}
#define AugerCommand_init_zero                   {false, 0, _ServoState_MIN, _ServoState_MIN}
#define AugerData_init_zero                      {_ServoState_MIN, _ServoState_MIN, 0, 0}
#define LinearSliderCommand_init_zero            {0}
#define LinearSliderData_init_zero               {0}
#define ScienceCommand_init_zero                 {0, _PumpState_MIN, _CarouselCommand_MIN, 0, 0, 0, _ScienceState_MIN, false, Version_init_zero, false, AugerCommand_init_zero, false, LinearSliderCommand_init_zero}
#define ScienceData_init_zero                    {0, _ScienceState_MIN, 0, 0, 0, false, Version_init_zero, false, AugerData_init_zero, false, LinearSliderData_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define AugerCommand_speed_rpm_tag               1
#define AugerCommand_upper_servo_tag             2
#define AugerCommand_lower_servo_tag             3
#define AugerData_lower_servo_tag                1
#define AugerData_upper_servo_tag                2
#define AugerData_distance_to_ground_cm_tag      3
#define AugerData_current_tag                    4
#define LinearSliderCommand_clear_stallstop_tag  1
#define LinearSliderData_is_stalled_tag          1
#define ScienceCommand_carousel_motor_tag        1
#define ScienceCommand_pumps_tag                 4
#define ScienceCommand_carousel_tag              7
#define ScienceCommand_calibrate_tag             8
#define ScienceCommand_stop_tag                  9
#define ScienceCommand_sample_tag                10
#define ScienceCommand_state_tag                 11
#define ScienceCommand_version_tag               12
#define ScienceCommand_auger_tag                 13
#define ScienceCommand_linear_slider_tag         14
#define ScienceData_sample_tag                   1
#define ScienceData_state_tag                    2
#define ScienceData_co2_tag                      3
#define ScienceData_humidity_tag                 4
#define ScienceData_temperature_tag              5
#define ScienceData_version_tag                  6
#define ScienceData_auger_tag                    7
#define ScienceData_linear_slider_tag            8

/* Struct field encoding specification for nanopb */
#define AugerCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    speed_rpm,         1) \
X(a, STATIC,   SINGULAR, UENUM,    upper_servo,       2) \
X(a, STATIC,   SINGULAR, UENUM,    lower_servo,       3)
#define AugerCommand_CALLBACK NULL
#define AugerCommand_DEFAULT NULL

#define AugerData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    lower_servo,       1) \
X(a, STATIC,   SINGULAR, UENUM,    upper_servo,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    distance_to_ground_cm,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    current,           4)
#define AugerData_CALLBACK NULL
#define AugerData_DEFAULT NULL

#define LinearSliderCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     clear_stallstop,   1)
#define LinearSliderCommand_CALLBACK NULL
#define LinearSliderCommand_DEFAULT NULL

#define LinearSliderData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     is_stalled,        1)
#define LinearSliderData_CALLBACK NULL
#define LinearSliderData_DEFAULT NULL

#define ScienceCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    carousel_motor,    1) \
X(a, STATIC,   SINGULAR, UENUM,    pumps,             4) \
X(a, STATIC,   SINGULAR, UENUM,    carousel,          7) \
X(a, STATIC,   SINGULAR, BOOL,     calibrate,         8) \
X(a, STATIC,   SINGULAR, BOOL,     stop,              9) \
X(a, STATIC,   SINGULAR, INT32,    sample,           10) \
X(a, STATIC,   SINGULAR, UENUM,    state,            11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,          12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  auger,            13) \
X(a, STATIC,   OPTIONAL, MESSAGE,  linear_slider,    14)
#define ScienceCommand_CALLBACK NULL
#define ScienceCommand_DEFAULT NULL
#define ScienceCommand_version_MSGTYPE Version
#define ScienceCommand_auger_MSGTYPE AugerCommand
#define ScienceCommand_linear_slider_MSGTYPE LinearSliderCommand

#define ScienceData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    sample,            1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2) \
X(a, STATIC,   SINGULAR, FLOAT,    co2,               3) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          4) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  auger,             7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  linear_slider,     8)
#define ScienceData_CALLBACK NULL
#define ScienceData_DEFAULT NULL
#define ScienceData_version_MSGTYPE Version
#define ScienceData_auger_MSGTYPE AugerData
#define ScienceData_linear_slider_MSGTYPE LinearSliderData

extern const pb_msgdesc_t AugerCommand_msg;
extern const pb_msgdesc_t AugerData_msg;
extern const pb_msgdesc_t LinearSliderCommand_msg;
extern const pb_msgdesc_t LinearSliderData_msg;
extern const pb_msgdesc_t ScienceCommand_msg;
extern const pb_msgdesc_t ScienceData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AugerCommand_fields &AugerCommand_msg
#define AugerData_fields &AugerData_msg
#define LinearSliderCommand_fields &LinearSliderCommand_msg
#define LinearSliderData_fields &LinearSliderData_msg
#define ScienceCommand_fields &ScienceCommand_msg
#define ScienceData_fields &ScienceData_msg

/* Maximum encoded size of messages (where known) */
#define AugerCommand_size                        9
#define AugerData_size                           14
#define LinearSliderCommand_size                 2
#define LinearSliderData_size                    2
#define SCIENCE_PB_H_MAX_SIZE                    ScienceData_size
#define ScienceCommand_size                      65
#define ScienceData_size                         72

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
